#!/usr/bin/env python

"""
filter incoming lines based on the 'note:' tag

Intended for use with the note add-on for todotxt - https://github.com/mgarrido/todo.txt-cli/tree/note/todo.actions.d

If you need multiple filters take a look at multiFilter

Colors the 'note:' tag green
"""

import sys
import re

from colorama import Fore, Style

pattern = re.compile(r"(note:[^ ]*)")

def main(args=None):
    for line in sys.stdin:
        print re.sub(pattern, Fore.GREEN + '\\1' + Style.RESET_ALL, line.strip())
    return True

if __name__ == "__main__":
    status = not main(sys.argv)
    sys.exit(status)
